print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "D:/GitHubRepos/Altar Diorama/AltarEnvironment/Assets/Maya_Models/Circle benches_M.mb"`)
{		
	file -o "D:/GitHubRepos/Altar Diorama/AltarEnvironment/Assets/Maya_Models/Circle benches_M.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "D:/GitHubRepos/Altar Diorama/AltarEnvironment/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "D:/GitHubRepos/Altar Diorama/AltarEnvironment/Temp/CommandPipe";

$donepipeKill = `fopen "D:/GitHubRepos/Altar Diorama/AltarEnvironment/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
